version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "3002:3002"
    container_name: user-service
    environment:
      - USER_SERVICE_PORT=3002
      - MONGO_USER_SERVICE_URL=mongodb://mongo:27017/users
      - PRODUCT_SERVER_URL=http://localhost:3001
      - CORS_ORIGINS=http://localhost:3002,http://localhost:3001
    depends_on:
      - mongo
    networks:
      - app-network

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "3001:3001"
    container_name: product-service
    environment:
      - USER_SERVICE_PORT=3001
      - MONGO_USER_SERVICE_URL=mongodb://mongo:27017/products
      - USER_SERVER_URL=http://localhost:3002
      - CORS_ORIGINS=http://localhost:3002,http://localhost:3001
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - product-service
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge