version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: ./user-service/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - USER_SERVICE_PORT=3002
      - MONGO_USER_SERVICE_URL=mongodb://mongo:27017/users
      - PRODUCT_SERVER_URL=http://localhost:3001
      - CORS_ORIGINS=http://localhost:3002,http://localhost:3001
    depends_on:
      - mongo

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - USER_SERVICE_PORT=3001
      - MONGO_USER_SERVICE_URL=mongodb://mongo:27017/products
      - USER_SERVER_URL=http://localhost:3002
      - CORS_ORIGINS=http://localhost:3002,http://localhost:3001
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
